version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "HoteldddDB"
    ports:
      - "1433:1433"
