// <auto-generated />
using Chambre_API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChambreAPI.Migrations
{
    [DbContext(typeof(ChambreContext))]
    partial class ChambreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chambre_API.Model.Chambre", b =>
                {
                    b.Property<int>("ChambreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChambreID"));

                    b.Property<int>("TypeChambreID")
                        .HasColumnType("int");

                    b.HasKey("ChambreID");

                    b.HasIndex("TypeChambreID");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("Chambre_API.Model.EquipementChambre", b =>
                {
                    b.Property<int>("EquipementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipementID"));

                    b.Property<string>("NomEquipement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeChambreID")
                        .HasColumnType("int");

                    b.HasKey("EquipementID");

                    b.HasIndex("TypeChambreID");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("Chambre_API.Model.TypeChambre", b =>
                {
                    b.Property<int>("TypeChambreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeChambreID"));

                    b.Property<string>("NomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrixParNuit")
                        .HasColumnType("real");

                    b.HasKey("TypeChambreID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Chambre_API.Model.Chambre", b =>
                {
                    b.HasOne("Chambre_API.Model.TypeChambre", "TypeChambre")
                        .WithMany("Chambres")
                        .HasForeignKey("TypeChambreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeChambre");
                });

            modelBuilder.Entity("Chambre_API.Model.EquipementChambre", b =>
                {
                    b.HasOne("Chambre_API.Model.TypeChambre", "TypeChambre")
                        .WithMany("Equipements")
                        .HasForeignKey("TypeChambreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeChambre");
                });

            modelBuilder.Entity("Chambre_API.Model.TypeChambre", b =>
                {
                    b.Navigation("Chambres");

                    b.Navigation("Equipements");
                });
#pragma warning restore 612, 618
        }
    }
}
